# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='bands',
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(related_name='bands', to='band.Genre'),
        ),
    ]
