# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20171005_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='genre',
            new_name='genres',
        ),
    ]
