# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(verbose_name='Time and date')),
                ('monetary_offer', models.IntegerField()),
                ('approved_by_head_booker', models.BooleanField(default=False)),
                ('approved_by_manager', models.BooleanField(default=False)),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='band.Band')),
                ('booker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booker', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concert.Stage')),
            ],
        ),
    ]
