# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=2048)),
            ],
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.AddField(
            model_name='concert',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concert.Stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='notes',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concert.Manager'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concert.Band'),
        ),
        migrations.AddField(
            model_name='employment',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.Concert'),
        ),
        migrations.AddField(
            model_name='employment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concert',
            name='techs',
            field=models.ManyToManyField(through='concert.Employment', to=settings.AUTH_USER_MODEL),
        ),
    ]
