# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='preparation_start',
            field=models.DateTimeField(null=True, verbose_name='Start of preparations'),
        ),
        migrations.AddField(
            model_name='concert',
            name='takedown_end',
            field=models.DateTimeField(null=True, verbose_name='End of takedown (ie. the stage is free)'),
        ),
        migrations.AddField(
            model_name='concert',
            name='time_end',
            field=models.DateTimeField(null=True, verbose_name='Time for the expected end'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='time',
            field=models.DateTimeField(verbose_name='Time and date for start of concert'),
        ),
    ]
